version: '2'
services:
  postgres:
    image: postgres:9.6.2
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=vagrant
      - POSTGRES_PASSWORD=vagrant
      - POSTGRES_DB=graphql
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
